<?php

use Blog\Model\Entity\PostEntity;

/**
 * @var $posts array
 * @var $post PostEntity
 * @var $paginateData array
 * @var $search string
 */

$this->headTitle('Posts list');

$form = $this->form;
$form->get('search')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Search'
]);
$form->get('submit')->setAttributes(['class'=>'btn btn-outline-primary float-right']);
$form->prepare();

?>

<h1>
    Posts
    <a class="btn btn-primary float-right" href="<?= $this->url('post/add'); ?>">
        Add Post
    </a>
</h1>

<br>

<?= $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-11">
        <div class="form-group">
            <?= $this->formElement($form->get('search')); ?>
        </div>
    </div>
    <div class="col-md-1">
        <?= $this->formElement($form->get('submit')); ?>
    </div>
</div>
<?= $this->form()->closeTag(); ?>

<br>

<?php if ($paginateData['allPages'] > 0 && $paginateData['currentPage'] <= $paginateData['allPages']): ?>
    <p>
        Showing <?= $paginateData['start'] ?> to <?= $paginateData['end'] ?> of <?= $paginateData['total'] ?> items.
    </p>
<?php else: ?>
    <h3>
        There isn't any post!
    </h3>
<?php endif; ?>

<?php $index = $paginateData['start']; ?>
<?php foreach($posts as $post): ?>
    <hr>
    <div class="row">
        <div class="col-md-1">
            <b><?= $index++ ?></b>
        </div>
        <div class="col-md-9">
            <a href="<?= $this->url('post/view', ['id'=>$post->getId()]); ?>">
                <h3 style="
                    display: -webkit-box;
                    -webkit-line-clamp: 1;
                    -webkit-box-orient: vertical;
                    overflow: hidden;
                    text-overflow: ellipsis;">
                    <?= $this->escapeHtml($post->getTitle()); ?>
                </h3>
            </a>
            <p>
                <b style="font-size: 20px"><?= $post->getUser()->getName() ?></b> &nbsp <?= $this->escapeHtml(date('d M Y H:i:s', strtotime($post->getCreatedAt()))); ?>
            </p>
            <p style="
                display: -webkit-box;
                -webkit-line-clamp: 2;
                -webkit-box-orient: vertical;
                overflow: hidden;
                text-overflow: ellipsis;">
                <?= $this->escapeHtml($post->getContext()); ?>
            </p>
        </div>
        <div class="col-md-2">
            <span class="float-right">
                <a class="btn btn-success" href="<?= $this->url('post/edit', ['id'=>$post->getId()]); ?>">Edit</a>
                <a class="btn btn-danger" href="<?= $this->url('post/delete', ['id'=>$post->getId()]); ?>">Delete</a>
            </span>
        </div>
    </div>
<?php endforeach; ?>

<?php if ($paginateData['allPages'] > 1 && $paginateData['currentPage'] <= $paginateData['allPages']): ?>
    <hr>
    <?php
    $searchLink = "&search=$search";
    ?>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item <?php if ($paginateData['currentPage'] == 1) echo 'disabled'; ?>">
                <a class="page-link" href="?page=<?php echo $paginateData['currentPage'] - 1 . $searchLink; ?>" tabindex="-1">Previous</a>
            </li>

            <?php
            for($page = 1; $page <= $paginateData['allPages']; $page++) {
                echo '<li class="page-item' . ($page == $paginateData['currentPage'] ? ' disabled' : '') . '">';
                echo '<a class="page-link"  href = "?page=' . $page . $searchLink . '">' . $page . ' </a>';
                echo '</li>';
            }
            ?>

            <li class="page-item <?php if ($paginateData['currentPage'] == $paginateData['allPages']) echo 'disabled'; ?>">
                <a class="page-link" href="?page=<?php echo $paginateData['currentPage'] + 1 . $searchLink; ?>">Next</a>
            </li>
        </ul>
    </nav>

<?php endif; ?>